#ifndef CATQUOTE_DATA_SUPER_QUOTE_UUID_GENERATOR_H
#define CATQUOTE_DATA_SUPER_QUOTE_UUID_GENERATOR_H

class QuoteUUIDGenerator {
public:
    QuoteUUIDGenerator();
};

#endif //CATQUOTE_DATA_SUPER_QUOTE_UUID_GENERATOR_H
